name: Bump version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver type of new version (major / minor / patch)'
        required: true
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout main
          uses: actions/checkout@v3.2.0
        - name: Setup Node.js Environment
          uses: actions/setup-node@v3.5.1
          with:
              node-version: 19.3.0
        - name: Setup Git
          run: |
            git config user.name '${{secrets.MAINTAINER_NAME}}'
            git config user.email '${{secrets.MAINTAINER_EMAIL}}'
        - name: Bump version
          run: npm version ${{ github.event.inputs.version }}
        - name: Push latest version
          run: git push --follow-tags