name: Continuous Integration
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - templates/**
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - templates/**
jobs:
  checks:
    runs-on: ${{ matrix.os }}
  strategy:
    matrix:
      os:
        - ubuntu-latest
        - windows-latest
      node-version:
        - 17.x
        - 18.x
        - 19.x
  steps:
    - name: Checkout files
      uses: actions/checkout@v2.6.0
    - name: Setup Node.js Environment
      uses: actions/setup-node@v3.5.1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci
    - name: Build
      run: npm run check
    - name: ESLint
      run: npm run lint
    - name: Prettier
      run: npm run style
