name: Format Code
on:
  push:
    branches:
      - main
    paths:
      - src/**
  workflow_dispatch:
jobs:
  format_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3.2.0
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Setup Node.js Environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 19.3.0
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Format code
        run: npm run fix
      - name: Setup Git
        run: |
          git config --global user.name 'Prettifier'
          git config --global user.email 'prettifier@users.noreply.github.com'
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git commit -am "Prettified the code yo."
          git push
